### PR TITLE
Cross platform compatibility (fixes Windows path resolving)

### PR DESCRIPTION
**Pull request by siready**
This pull request fixes file path resolving on Windows.

For more info see:
* [Tips for Writing Portable Node.js Code](https://gist.github.com/domenic/2790533)
* [File URIs in Windows](http://blogs.msdn.com/b/ie/archive/2006/12/06/file-uris-in-windows.aspx)

### CODE REVIEW

**Comment by Gu1** [comment]
Hello !
Thanks for the pull request.
I see you changed the regexp that removes turns the file URI into a path (```file:\/\/``` to ```file:\/{2,3}```) and called path.resolve on it.
This seem to be breaking things on linux, since the path is absolute:

```
> jspm.normalize('wut').then(function(filePath) { console.log(filePath.replace(/file:\/\/(.*?)(\.js)?$/, '$1')); });
/home/gu1/Desktop/idcware/node-sass-jspm-importer/test_jspm/olol

> jspm.normalize('wut').then(function(filePath) { console.log(path.resolve(filePath.replace(/file:\/{2,3}(.*?)(\.js)?$/, '$1'))); });
/home/me/node-sass-jspm-importer/test_jspm/home/me/node-sass-jspm-importer/test_jspm/wut
```

**Comment by siready** [comment]
Hey!

Currently I don't have any unix environment set so I wasn't able to test it. Was expecting tests to do it for me :)

Could you maybe show me console log of path without path.resolve?
Absolute path should be fine, since libsass uses absolute paths anyway.

**Comment by Gu1** [comment]
Without path.resolve, it's just ```home/me/node-sass-jspm-importer/test_jspm/wut``` witout a trailing slash, because of the ```file:\/{2,3}``` which eats the first ```/```.

**Comment by siready** [comment]
Thanks, it makes sense. I'll get into it when I get home.

**Comment by siready** [comment]
Could you please check what's going on after last commit? I was trying to simulate it with path.posix.normalize which gave me correct results.

I'm also wondering if functions.js file has to be modified? Importing works OK when not defining functions object literal property for node-sass.

**Comment by Gu1** [comment]
It seems to be working, yeah.
But calling path.normalize on the URI itself is a bit ugly no ?

Maybe we could just rely on a module [like this one](https://github.com/TooTallNate/file-uri-to-path) to do the uri to path conversion.

I'm not sure I understand the last part of your question about functions.js. It very possibly will have to be modified too. I don't have a windows machine available to test whether it works or not.

**Comment by Gu1** [comment]
@siready, I merged your pull request, and then replaced the URI-conversion regex with the [function used internally by JSPM to convert URI to paths](https://github.com/jspm/jspm-cli/blob/master/lib/common.js#L28)
Could you test it on windows and tell me how it works ? :
https://github.com/idcware/node-sass-jspm-importer/commit/9d1322dfe2d10b27c513a3a52aa821b2323a7364

**Comment by siready** [comment]
Hey, unfortunately it didn't work.
I agree with you that calling path.normalize on the file URI is ugly since it wasn't supposed to work with it. That module looks great to me, I found it at the time, but it seamed a bit too much for our reasons. Since URI is returned by jspm anyway I also think using their way is the best way to go.

I've opened new pull request (#6) with the changes with the fixes for cross-platform path issue. Now we can call path.normalize with confidence since we already have path and not URI.

**Pull request merged**
